
class NotFound(Exception):
    pass

class SaveError(Exception):
    pass
